version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/maindb
      - BESU_NODE_URL=http://besu-node-0:8545
      - CONTRACT_ADDRESS=
      - PRIVATE_KEY=
    depends_on:
      - postgres
    networks:
      - besu_network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: maindb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - besu_network

volumes:
  postgres_data:

networks:
  besu_network:
    external: true