version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - ENV=production
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/maindb
    volumes:
      - .:/app
      - /app/tmp
    depends_on:
      - postgres
    networks:
      - besu_network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: maindb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  besu_network:
    external: true